### ISSUE TITLE
Nothing working with latest server

### ISSUE THREAD

**Issue by Ruined1** [ENDrain/vRP-plusplus#11]
I added the vrp folder with all included files/folder to the resources folder, and referenced it in the server config, but there's absolutely nothing displaying when logged into the server. Pressing M does nothing, and there aren't any blips on the radar. Perhaps I'm confused as to how this all works? My steam ID is set to admin in the server configuration. I'm using the latest FX-server `#290-04e034829f75169f11ee33abf67281ecd74728e3`

Thanks for helping out. This is an amazing looking framework, and I appreciate any effort you can put into a first-timer FiveM admin.

Edit: I'm beginning to think you wrote this for CitizenMP and that's why errors are being thrown in FX
Edit 2: I'm thinking it's because I'm an idiot and didn't have MySQL setup ;) long story, but I'll report back if issue persists
Edit 3: Nope, same issue even with proper DB access.

> Error loading script base.lua in resource vrp: base.lua:2: attempt to call a nil value (global 'require')
> stack traceback:
>         base.lua:2: in main chunk
> Failed to load script base.lua.

> Error loading script modules/group.lua in resource vrp: modules/group.lua:9: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/group.lua:9: in main chunk
> Failed to load script modules/group.lua.

> Error loading script modules/admin.lua in resource vrp: modules/admin.lua:1: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/admin.lua:1: in main chunk
> Failed to load script modules/admin.lua.

> Error loading script modules/gui.lua in resource vrp: modules/gui.lua:1: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/gui.lua:1: in main chunk
> Failed to load script modules/gui.lua.

> Error loading script modules/survival.lua in resource vrp: modules/survival.lua:1: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/survival.lua:1: in main chunk
> Failed to load script modules/survival.lua.

> Error loading script modules/player_state.lua in resource vrp: modules/player_state.lua:1: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/player_state.lua:1: in main chunk
> Failed to load script modules/player_state.lua.

> Error loading script modules/map.lua in resource vrp: modules/map.lua:10: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/map.lua:10: in main chunk
> Failed to load script modules/map.lua.

> Error loading script modules/money.lua in resource vrp: modules/money.lua:1: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/money.lua:1: in main chunk
> Failed to load script modules/money.lua.

> Error loading script modules/inventory.lua in resource vrp: modules/inventory.lua:1: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/inventory.lua:1: in main chunk
> Failed to load script modules/inventory.lua.

> Error loading script modules/identity.lua in resource vrp: modules/identity.lua:1: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/identity.lua:1: in main chunk
> Failed to load script modules/identity.lua.

> Error loading script modules/business.lua in resource vrp: modules/business.lua:4: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/business.lua:4: in main chunk
> Failed to load script modules/business.lua.

> Error loading script modules/item_transformer.lua in resource vrp: modules/item_transformer.lua:7: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/item_transformer.lua:7: in main chunk
> Failed to load script modules/item_transformer.lua.

> Error loading script modules/emotes.lua in resource vrp: modules/emotes.lua:4: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/emotes.lua:4: in main chunk
> Failed to load script modules/emotes.lua.

> Error loading script modules/police.lua in resource vrp: modules/police.lua:3: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/police.lua:3: in main chunk
> Failed to load script modules/police.lua.

> Error loading script modules/home.lua in resource vrp: modules/home.lua:4: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/home.lua:4: in main chunk
> Failed to load script modules/home.lua.

> Error loading script modules/home_components.lua in resource vrp: modules/home_components.lua:3: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/home_components.lua:3: in main chunk
> Failed to load script modules/home_components.lua.

> Error loading script modules/mission.lua in resource vrp: modules/mission.lua:3: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/mission.lua:3: in main chunk
> Failed to load script modules/mission.lua.

> Error parsing script modules/atm_finder.lua in resource vrp: modules/atm_finder.lua:9: ')' expected near 'function'
> Failed to load script modules/atm_finder.lua.

> Error loading script modules/debug.lua in resource vrp: modules/debug.lua:2: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/debug.lua:2: in main chunk
> Failed to load script modules/debug.lua.

> Error loading script modules/aptitude.lua in resource vrp: modules/aptitude.lua:4: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/aptitude.lua:4: in main chunk
> Failed to load script modules/aptitude.lua.

> Error loading script modules/basic_phone.lua in resource vrp: modules/basic_phone.lua:4: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/basic_phone.lua:4: in main chunk
> Failed to load script modules/basic_phone.lua.

> Error loading script modules/basic_atm.lua in resource vrp: modules/basic_atm.lua:4: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/basic_atm.lua:4: in main chunk
> Failed to load script modules/basic_atm.lua.

> Error loading script modules/basic_market.lua in resource vrp: modules/basic_market.lua:3: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/basic_market.lua:3: in main chunk
> Failed to load script modules/basic_market.lua.

> Error loading script modules/basic_gunshop.lua in resource vrp: modules/basic_gunshop.lua:3: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/basic_gunshop.lua:3: in main chunk
> Failed to load script modules/basic_gunshop.lua.

> Error loading script modules/basic_garage.lua in resource vrp: modules/basic_garage.lua:4: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/basic_garage.lua:4: in main chunk
> Failed to load script modules/basic_garage.lua.

> Error loading script modules/basic_items.lua in resource vrp: modules/basic_items.lua:2: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/basic_items.lua:2: in main chunk
> Failed to load script modules/basic_items.lua.

> Error loading script modules/basic_skinshop.lua in resource vrp: modules/basic_skinshop.lua:3: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/basic_skinshop.lua:3: in main chunk
> Failed to load script modules/basic_skinshop.lua.

> Error loading script modules/cloakroom.lua in resource vrp: modules/cloakroom.lua:3: attempt to index a nil value (global 'vRP')
> stack traceback:
>         modules/cloakroom.lua:3: in main chunk
> Failed to load script modules/cloakroom.lua.

> Error loading script modules/survival_reverse.lua in resource vrp: modules/survival_reverse.lua:1: attempt to call a nil value (global 'require')
> stack traceback:
>         modules/survival_reverse.lua:1: in main chunk
> Failed to load script modules/survival_reverse.lua.

> Started resource vrp

**Comment by ENDrain** [comment]
Yes, vRP++ is out of date as of the moment. I’m working on porting it to FXServer, slowly because of life matters.

**Comment by Ruined1** [comment]
I understand completely. Thanks for the reply!
