### ISSUE TITLE
robberies would be amazing aswell as traffic,

### ISSUE THREAD

**Issue by chubbynugly** [ENDrain/vRP-plusplus#4]
if you could add robberies and traffic syncing that would be really cool!

I can donate.

**Comment by ENDrain** [comment]
I'd like very much to add robberies, but I just don't know where to start. I'm certain there's no way to add robberies from GTA Online, or it's outside of vRP's scope anyway (more like a FiveM mod). Do you have any ideas about robberies, how they could work in vRP?

And what do you mean by traffic syncing?

**Comment by NickWatsonMan** [comment]
Okay, here is the solution. Simply just write robberies in your code. I mean, really. Like they are written in online. 

Okay, another way is... I don't really know how it all works, but what if you try to use missions from single-player? There are some good robberies.

**Comment by chubbynugly** [comment]
yeah, I know how and I could explain to you if you would like, what is your discord, and traffic syncing by letting admin lower the damn traffic that causes so much lag lol

**Comment by ENDrain** [comment]
@chubbynugly  Discord is @endrain. You mean, the NPC traffic? I'm afraid that's again ouf of vRP's scope. I'm looking to do some FiveM modding, but not right now.

**Comment by chubbynugly** [comment]
I need the numbers after your name lol

**Comment by ENDrain** [comment]
Don't use discord much lol
0997

**Comment by chubbynugly** [comment]
sent

**Comment by ENDrain** [comment]
I’m eaving this open until I work something out. Please, post your ideas if you have any

**Comment by ENDrain** [comment]
It appears that Imagick created a very cool Mission system for the framework, which allows for almost any kind of activities you can think of. I’m going to create an example mission and add some instructions as to how to create missiona and what you can do with then. If you ever have any new ideas about thefts and this kind of stuff, re-open the issue.

**Comment by NegativeFeedback** [comment]
I am adding atm robberies using the harvest function in the area of atm and you can rob it for some money over time the only issue is im adding a notification bit to the harvest setup so cops get a alarm
