### ISSUE TITLE
anything that has to do with closest player

### ISSUE THREAD

**Issue by NegativeFeedback** [ENDrain/vRP-plusplus#6]
![image](https://user-images.githubusercontent.com/1072659/27989882-3c7e71c2-640a-11e7-8f92-677b0816a6b4.png)
so give money and give items for sure this happens

**Comment by NegativeFeedback** [comment]
Happens with admin menu call coordinates as well

**Comment by ENDrain** [comment]
Thanks for the report, will investigate

**Comment by NegativeFeedback** [comment]
cool thanks let me know if you need any more info, I have not been able to figure it out still

**Comment by ENDrain** [comment]
Please try the current build. I noticed that tunnel returning values thing doesn't work as expected, so I pulled it back. I'm curious if it fixes your problem

**Comment by NegativeFeedback** [comment]
will give it a shot tonight

**Comment by NegativeFeedback** [comment]
ok yes looks like this part is fixed ill open new tickets for other stuff
