### ISSUE TITLE
[Feature] Display bank balance

### ISSUE THREAD

**Issue by WingedHussarr** [ENDrain/vRP-plusplus#7]
Add a bank balance gui similar to the wallet money one

**Comment by ENDrain** [comment]
Ok, thanks for the idea! I think I’ll add it in the menu, lke a bank app in your phone

**Comment by ENDrain** [comment]
Forgot that in GTA Online you can see both in up right corner. Let's say I question whether it's ok for roleplay, but let it stay like that for now.
