### ISSUE TITLE
garage and markets disappeared

### ISSUE THREAD

**Issue by NegativeFeedback** [ENDrain/vRP-plusplus#8]
the only thing that shows up on the map now is houses and city hall and jobs, no atm garages or markets

**Comment by NegativeFeedback** [comment]
, not seeing anything in the log about why

**Comment by NegativeFeedback** [comment]
![image](https://user-images.githubusercontent.com/1072659/28348937-72f7334e-6c05-11e7-9353-82f7358fe296.png)

**Comment by ENDrain** [comment]
Do you have a lot of blips? Like, more than 50? Closer to 100? I heard there're issues with a big number of blips. I have that in my list

**Comment by NegativeFeedback** [comment]
no its is just a few more than default vrp

**Comment by ENDrain** [comment]
Fixed. Was just a small typo, leftover from parralel branch

**Comment by NegativeFeedback** [comment]
cool ill give it a shoot soon.

**Comment by NegativeFeedback** [comment]
fixed
